### ISSUE TITLE
Dropping attachments in FilePond from Thunderbird (Firefox)

### ISSUE THREAD

**Issue by simusr2** [pqina/filepond-plugin-file-encode#11]
I'm trying to drop attachments from Thunderbird but in Firefox it doesn't work.
With Google Chrome it works well.

Chrome 81
Firefox 76
Thunderbird 68

[Example.zip](https://github.com/pqina/filepond-plugin-file-encode/files/4591465/Example.zip)

**Comment by rikschennink** [comment]
Hi, this is not the correct repository, drag dropping from other applications isn't very well supported by browsers at this point.
