### ISSUE TITLE
Multiple image upload fails with file-encode

### ISSUE THREAD

**Issue by Suedo** [pqina/filepond-plugin-file-encode#13]
When uploading images, I am console logging dataUrl of each. This works well when uploading one at a time. But, When doing multiple file upload at once, most of the file uploads fails in the method `getFileEncodeDataURL`, and only one gets uploaded.

My `onaddfile` method handler:
```ts
  const filedAdded = (err, file) => {
    if (err) console.log('error on adding file');
    else {
      const fileDataUrl: string = file.getFileEncodeDataURL(); // fails here
      const extractionRegex = /^data:image\/(\w+);base64,(.+)$/;
      const groups = fileDataUrl.match(extractionRegex);
      console.log('file type: ', groups && groups[1]);
      setFiles((files) => [...files, file]);
    }
  };
```
The specific error is :

![image](https://user-images.githubusercontent.com/4963779/84588914-da34e780-ae48-11ea-8d59-2e2bedc91a58.png)

I thought of updating the source code with a guard, as present in `getFileEncodeBase64String`, but then, the upload just silently fails. Only a subset of the total number of parallel upload succeeds. 

```js
    addFilter(
        'DID_CREATE_ITEM', (item, { query }) => {
            
            if (!query('GET_ALLOW_FILE_ENCODE')) return;

            item.extend('getFileEncodeBase64String', () => base64Cache[item.id] && base64Cache[item.id].data);
            // guard here results in silent fails , so skipped it
            item.extend('getFileEncodeDataURL', () => `data:${item.fileType};base64,${base64Cache[item.id].data}`);
        }
    );
```

I tried setting the `maxParallelUploads` property to 1, but that also did not help.

Please let me know if I'm doing something wrong.

**Comment by rikschennink** [comment]
The latest version of the plugin has a guard in place to prevent this error. The file-encode plugin is mainly there to handle synchronous uploads and while the above functions exist the data might not be ready yet when they're called.

Why do you need the dataURL to upload images?

**Comment by Suedo** [comment]
I tried with the latest version only. It doesn't work 😢  Kindof Expected as the PR that went into the latest version (2.1.6) was one I raised 🥳 

I am not uploading the images using '/server' option. I am getting the dataUrl, and saving it in my global store. Later on, I will be sending the file type and base64 data from the dataURL to a backend endpoint along with a bunch of form data, which updates the form data in mongo, and the image data in AWS S3.

Link to full code: [here](https://github.com/Suedo/MobX2020/tree/draftjs-test)

Below is my ImageUpload **container**, which saves the base64 data and image file type extracted from the data URL, into a global store.  
```ts
export const ImgUploader = () => {
  const initialState: any[] = []; // to avoid state being set to 'never' type, https://stackoverflow.com/a/52423919/2715083
  const [images, setImages] = useState(initialState);

  const { imagesStore } = useStore();

  const updateFiles = (updatedImagesFromChild: any[]) => {
    setImages((images) => updatedImagesFromChild);
    // Issue area
    const updatedImages: UploadImage[] = updatedImagesFromChild.map(getDataFromImage);
    imagesStore.updateImages(updatedImages);
  };

  return (
    <ImgUploadComponent
      onUpdateFiles={updateFiles}
      files={images}
      label="Drag & Drop images here, or click to open file browser!"
    ></ImgUploadComponent>
  );
};
```

And my ImageUpload **Component** :

```ts
export const ImgUploadComponent: FunctionComponent<ImgUploadComponentPropsI> = ({ label, files, onUpdateFiles }) => {
  const pondref = useRef();

  const disp = label || 'Drag & Drop your files or <span class="filepond--label-action">Browse</span>';

  const filesUpdated = (newFiles: any) => {
    onUpdateFiles(newFiles);
  };

  return (
    <FilePond
      ref={pondref}
      files={files}
      allowMultiple={true}
      onupdatefiles={filesUpdated}
      maxParallelUploads={1}
      acceptedFileTypes={['image/png', 'image/jpeg']}
      fileValidateTypeLabelExpectedTypesMap={{
        'image/jpeg': '.jpg',
        'image/png': '.png',
      }}
      labelIdle={disp}
    />
  );
};
```

My base64 extractor method:

```ts
// image is the filepond file-encoded image
export const getDataFromImage = (image: any) => {
  const fileDataUrl: string = image.getFileEncodeDataURL(); // fails here
  const extractionRegex = /^data:image\/(\w+);base64,(.+)$/;
  const groups = fileDataUrl.match(extractionRegex);
  const newImage: UploadImage = {
    fileName: image.filename,
    fileType: (groups && groups[1]) || '',
    base64: (groups && groups[2]) || '',
  };
  return newImage;
};
```

**Comment by rikschennink** [comment]
@Suedo oooh :D Haha, I totally missed that, sorry :-)

I'll take a look later today.

**Comment by rikschennink** [comment]
This works: https://codesandbox.io/s/vanilla-filepond-file-encode-sfbsb?file=/src/index.js

Instead of `onaddfile` use `onpreparefile`

**Comment by Suedo** [comment]
Nice! Tried it out.. solves the original issue.

A few question on the usage:

the docs on `onpreparefile` says:

> File has been transformed by the transform plugin or another plugin subscribing to the prepare_output filter. It receives the file item and the output data.

I console logged the output, like so : `console.log('output:', JSON.stringify(output, null, 2));` and the result looked like this:

```ts
output: {
  "_relativePath": ""
}
```

If you could give some ideas on what this `output` is, and/or best ways to use it when uploading multiple files at once, would be a great help! 😸

**Comment by rikschennink** [comment]
`console.log('output:', JSON.stringify(output, null, 2));` why would you not just log the output (without stringifying it), then you could see it's a file object.

**Comment by Suedo** [comment]
Sometimes we just skip the most obvious things to do! 

Thanks for the answers :)

**Comment by Suedo** [comment]
Forgot to ask:

How does the `maxParallelUploads` play with all these ? 

I was using `onaddfile` as it gave the entire list of files, and it was straightforward to update my global store, for both file add, and removal cases. It would be nice to be able to use it. Can a fix be possible? or would you say it works as per design?

If so, what would be the suggested callback to use for when a file gets removed? If we are using `onpreparefile`

**Comment by rikschennink** [comment]
You can use `onremove` file, that's called when a file is removed. You can also use `onupdatefiles` to track updates to the files list.
