### ISSUE TITLE
Add support for typescript

### ISSUE THREAD

**Issue by kino90** [pqina/filepond-plugin-file-encode#14]
Hello, thanks for this lib and all of its plugins, i like it so much!

I saw some other plugins have Typescript support, but this one doesn't, why? Is this coming sooner or later? 
Thanks

**Comment by rikschennink** [comment]
The definition files are added by other devs, happy to accept a PR 👍

**Comment by kino90** [comment]
I've already done a definition file locally! It works, but I don't know how to extend `File` type with the two methods from the plugin 🤔 Any idea?

I'll submit a PR tomorrow morning!

**Comment by rikschennink** [comment]
Awesome!

I’m not sure, maybe take a look at how it’s done for the other plugins?

**Comment by kino90** [comment]
I saw the size validation plugin (if I remember correctly), but id doesn't add any method to the File istance.. I think this plugin is the only one which does that..

**Comment by rikschennink** [comment]
The crop plugin also does it 👍

**Comment by kino90** [comment]
Just checked that, but sadly also `filepond-plugin-image-crop` types does not extend File. I'll submit a PR soon 😉
