### ISSUE TITLE
TS1192 filepond-plugin-file-encode/types/index has no default export with npm 6.14.11

### ISSUE THREAD

**Issue by zaca** [pqina/filepond-plugin-file-encode#19]
ERROR in src/app/shared/components/forms/forms.module.ts:30:8 - error TS1192: Module '"/.../node_modules/filepond-plugin-file-encode/types/index"' has no default export.

npm version: 6.14.11

I found a workaround by setting 
"allowSyntheticDefaultImports": true, 
in tsconfig.app.json

**Comment by rikschennink** [comment]
Will close because this is probably not related to the type file.
