### ISSUE TITLE
Types are missing method definitions 

### ISSUE THREAD

**Issue by jkeuhlen** [pqina/filepond-plugin-file-encode#27]
The [docs](https://pqina.nl/filepond/docs/api/plugins/file-encode/) call out these two methods, but they seem to be missing the correspond type definitions. 

![image](https://github.com/pqina/filepond-plugin-file-encode/assets/10284802/83dc9a75-2a15-4ac7-b5c5-5aa22211aeb3)

I _think_ you only need to update this to be something like: 
```
// @ts-ignore
import { FilePondFile, FilePondOptions } from "filepond";

declare module "filepond" {
  export interface FilePondOptions {
    /** Enable or disable file encode. */
    allowFileEncode?: boolean;
  }

  export interface FilePondFile {
    getFileEncodeBase64String(): string;
    getFileEncodeDataURL(): string;
  }
}
``` 
and I'll open a pull request to that effect, but please let me know if I'm missing something!

**Comment by rikschennink** [comment]
Merged :)
