### ISSUE TITLE
Filepond encode doesnt work.

### ISSUE THREAD

**Issue by laurenceschellevisch** [pqina/filepond-plugin-file-encode#3]
Filepond Code:
![image](https://user-images.githubusercontent.com/17025778/47366053-24e67680-d6dd-11e8-9b47-da4e79808cea.png)

result:
![image](https://user-images.githubusercontent.com/17025778/47365407-ca98e600-d6db-11e8-8b77-1d5ada4eee02.png)

in the result I use the function getFiles(); to get the object in the browser like that.
My goal: Send a base64 String to my API 
The allowFileEncode doesn't work and I don't know how its supposed to work.

https://pqina.nl/filepond/docs/patterns/plugins/file-encode/

**Comment by rikschennink** [comment]
The File Encode plugin is used to encode the file object and store the resulting base64 string in a hidden input (which can then be submitted to the server using a classic form post).

The encoded data is not available in the file item itself. I would advise sending the file objects as multipart data.

If that's not possible you'll have to encode the files yourself or dig around in the internal HTML of FilePond to extract it there. Another option would be to fork the file encode plugin and alter the source code so it stores the encoded data in the file metadata object.

**Comment by alcferreira** [comment]
@rikschennink sorry for asking but I haven't found an issue about that... Why was [base64 removed from metadata?](https://github.com/pqina/filepond-plugin-file-encode/commit/f8c408f928995d442bccfb76d4469fc4443725c3) 
I was updating my filepond plugins and it won't work without the base64 that was previous retrieved from metadata... 

I'm using redux-form and I have some manual validations before "accepting" a new file so I need to set manually the redux-form field with the given base64...

Would it be possible to bring back the base64 into the metadata object?

**Comment by rikschennink** [comment]
@alcferreira It was in the metadata by accident, it should've never been in there so it was removed. The base64 data is still saved to the hidden input files inside the FilePond DOM tree.

The following call should return all hidden input fields within FilePond, each one relates to a file item.

```js
this.pond.element.querySelectorAll('input[type="hidden"]')
```

**Comment by alcferreira** [comment]
Ok @rikschennink thanks!

**Comment by kvssankar** [comment]
> Filepond Code:
> ![image](https://user-images.githubusercontent.com/17025778/47366053-24e67680-d6dd-11e8-9b47-da4e79808cea.png)
> 
> result:
> ![image](https://user-images.githubusercontent.com/17025778/47365407-ca98e600-d6db-11e8-8b77-1d5ada4eee02.png)
> 
> in the result I use the function getFiles(); to get the object in the browser like that.
> My goal: Send a base64 String to my API
> The allowFileEncode doesn't work and I don't know how its supposed to work.
> 
> https://pqina.nl/filepond/docs/patterns/plugins/file-encode/

did u get this resolved
please help me iam facingthe issue
