### ISSUE TITLE
Set the PROCESS_COMPLETE status to the file

### ISSUE THREAD

**Issue by francois-roget** [pqina/filepond-plugin-file-encode#4]
Hi,

Thanks for this amazing work.
I would like to use the file-encode plugin but I see a small possible improvement:
when we add a file, it gets base64 encoded but the status stays gray while it could be considered green (PROCCESS_COMPLETE).
Could you please make so that the file is green as soon as it is encoded.

Thanks
François

**Comment by rikschennink** [comment]
Hi,

The encode plugin doesn't work in the foreground and IMHO it's actions should therefore not be invisible to the user (when selecting a file in the classic file upload it doesn't change state either). 

When a file is dropped it's ready for upload.

**Comment by francois-roget** [comment]
Ok, thank for you input.
