### ISSUE TITLE
Disabling filepond encode leaves higher memory stack trace than if it was disabled

### ISSUE THREAD

**Issue by neskimoo** [pqina/filepond-plugin-file-encode#5]
We ran into an issue where we are using filepond to upload a video without using the server capabilities of filepond. We are just adding the file in to show the user that it is there and we subsequently process the file.

We had the encode plugin turned on for encoding images but noticed a large memory spike when trying to add a video to filepond. Once we determined that we didn't need to use encode for video, we turned the allowFileEncode flag to false in the options which greatly decreased the memory usage.

That being said, in our testing we removed the encode plugin and saw that the memory usage was much lower again than if the allowFileEncode flag is set to false. Both of these tests were done adding a 500MB file to filepond.

With allowFileEncode flag set to false:
![Screen Shot 2019-03-22 at 11 08 42](https://user-images.githubusercontent.com/8782036/54819172-f6bc9100-4c92-11e9-8b54-d2246b21f165.png)

With fileEncode plugin removed:
![Screen Shot 2019-03-22 at 11 08 08](https://user-images.githubusercontent.com/8782036/54819157-ec01fc00-4c92-11e9-8490-d660df120e7c.png)

Would you have any insight into why the memory usage is so different for when the encode plugin is in the main file but with the flag disabled and when the plugin isn't there at all?

Any help on this would be greatly appreciated!

**Comment by rikschennink** [comment]
Hi, just published version `2.1.3` which should address this issue.

Please note that encoding large files will indeed take up considerable amounts of memory.

**Comment by neskimoo** [comment]
Great, this fix worked perfectly! Thanks for the speedy turnaround on this!
