### ISSUE TITLE
Exception: Cannot set property 'data' of undefined

### ISSUE THREAD

**Issue by timashev** [pqina/filepond-plugin-file-encode#7]
Just got bug report from production server:

`TypeError: Cannot set property 'data' of undefined` at https://github.com/pqina/filepond-plugin-file-encode/blob/36b9cfb8705dacfc5f7b7100593c0b43c714d783/src/js/index.js#L50

So I would suggest to add a check that `base64Cache[item.id]` is not empty before trying to assign value to `base64Cache[item.id].data`.

**Comment by rikschennink** [comment]
Looks like the item was removed while the file was being encoded. PR is welcome.

**Comment by RahulAnand442001** [comment]
> Just got bug report from production server:
> 
> `TypeError: Cannot set property 'data' of undefined` at
> 
> https://github.com/pqina/filepond-plugin-file-encode/blob/36b9cfb8705dacfc5f7b7100593c0b43c714d783/src/js/index.js#L50
> 
> So I would suggest to add a check that `base64Cache[item.id]` is not empty before trying to assign value to `base64Cache[item.id].data`.

How did you resolve this issue. I am unable to get over it
