### ISSUE TITLE
base64 data not available on server: process  function. 

### ISSUE THREAD

**Issue by Paca** [pqina/filepond-plugin-file-encode#8]
Hello with following code:

    <body>
        <input type="file"
               class="filepond"
               name="filepond">    
        <script src="https://unpkg.com/filepond-polyfill/dist/filepond-polyfill.js"></script>
        <script src="https://unpkg.com/filepond-plugin-image-preview/dist/filepond-plugin-image-preview.js"></script>
        <script src="https://unpkg.com/filepond-plugin-file-metadata/dist/filepond-plugin-file-metadata.js"></script>
        <script src="https://unpkg.com/filepond-plugin-file-encode/dist/filepond-plugin-file-encode.js"></script>
        <script src="https://unpkg.com/filepond-plugin-file-validate-size/dist/filepond-plugin-file-validate-size.js"></script>

        <script src="https://unpkg.com/filepond/dist/filepond.js"></script>
        <script>

            FilePond.registerPlugin(
              FilePondPluginImagePreview,
              FilePondPluginFileMetadata,
              FilePondPluginFileEncode,
              FilePondPluginFileValidateSize
            );

            FilePond.setOptions({
                 server: {
                    process: (fieldName, file, metadata, load, error, progress, abort, transfer, options) => 
                      {

                        // fieldName is the name of the input field
                        // file is the actual file object to send
                        console.log(fieldName);
                        console.log(file);
                        //console.log(file.getFileEncodeBase64String());
                        console.log(file.name);
                        console.log(metadata);

                        // Should expose an abort method so the request can be cancelled
                        return {
                            abort: () => {
                                // User tapped abort, cancel our ongoing actions here

                                // Let FilePond know the request has been cancelled
                                abort();
                            }
                        }
                    }
                }
            });

            FilePond.create(
                document.querySelector('input'),
                {
                    labelIdle: 'Drag & Drop your image or <span class="filepond--label-action">Browse</span>',
                    imagePreviewHeight: 150,
                    allowFileEncode: true
                }
            );
        </script>
    </body>

I never see the data base64 in the file object. 
![image](https://user-images.githubusercontent.com/528350/65302398-60065980-db7b-11e9-8eb5-79dab9edb5a9.png)

Someone can help me to understood ?

Thank you

**Comment by rikschennink** [comment]
The file encode plugin stores the base64 data in hidden input fields for sync posting to the server. The `server` configuration block is for async uploading and only receives file objects not file items so does not have access to the base64 encoded data. You'd have to generate the base64 string inside the server block if you want to use that to upload the files.

**Comment by rikschennink** [comment]
closed because no response
