### ISSUE TITLE
This plugin also encodes files that came from the server

### ISSUE THREAD

**Issue by Evertt** [pqina/filepond-plugin-file-encode#9]
I would expect that if a file came from the server, as in it was added like:

```javascript
FilePond.create(element, {
    files: [
        source: 'test.jpg',
        options: {
            type: 'local',
        }
    ]
})
```

That then that file wouldn't get encoded in base64. Why would you waste that precious memory if you can just send back the filename? I can easily deduce on the backend that then it's a file I already have.

**Comment by rikschennink** [comment]
You're telling FilePond to fetch the file, it will then treat it like any other file object as it can be edited / etc.

If you just want to mock the file you can use this:

```js
const pond = FilePond.create({
    files: [
        {
            // the server file reference
            source: '12345',

            // set type to local to indicate an already uploaded file
            options: {
                type: 'local',

                // mock file information
                file: {
                    name: 'my-file.png',
                    size: 3001025,
                    type: 'image/png'
                }
            }
        }
    ]
});
```

**Comment by Evertt** [comment]
Ah, okay, I'll try that then. I hope that it will still show a preview in some way, because I wouldn't want to lose that feature.

**Comment by rikschennink** [comment]
You can use the poster plugin to achieve that

**Comment by Evertt** [comment]
Thanks, that works. I'm a bit disappointed that the poster looks completely different from the preview. I preferred to have them identical.

**Comment by rikschennink** [comment]
Maybe the fact that you're using a free product-set that has taken many months of development time to create (+ the fact that you're receiving free support) can somewhat alleviate that disappointment.

You're free to fork the image-preview plugin or filepond and improve / submit a PR request.

**Comment by Evertt** [comment]
Sorry man I didn't mean to sound ungrateful. I am actually grateful for you
having made this file uploader.
